using System;
using System.Collections.Generic;
namespace CodeMonkeyPlayerSetup
{
    internal static class InstallerText
    {
        internal static readonly string[] Keys = { "Title", "Intro", "Desktop", "Associations", "Language", "Folder", "Note", "Install", "Cancel", "Installing", "Done", "Restart", "Failed", "InvalidPath", "Log", "Close", "Cancelled" };
        private static readonly Dictionary<string, string[]> Texts = new Dictionary<string, string[]>
        {
            { "ko", new[] { "설치", "설치 언어와 옵션을 선택한 뒤 설치를 누르세요.", "바탕화면 바로가기 만들기", "동영상의 연결 프로그램으로 등록", "언어", "설치 폴더", "기존 기본 앱과 개인 언어 설정은 유지됩니다. 설치에는 관리자 권한이 필요합니다.", "설치", "취소", "설치 중입니다. 잠시 기다려 주세요.", "설치가 완료되었습니다.", "설치가 완료되었습니다. 나중에 Windows를 다시 시작해 주세요.", "설치하지 못했습니다. 아래 로그에서 자세한 내용을 확인하세요.", "올바른 로컬 설치 폴더의 전체 경로를 입력하세요.", "설치 로그", "닫기", "설치가 취소되었습니다." } },
            { "en", new[] { "Setup", "Choose a language and options, then click Install.", "Create a desktop shortcut", "Register in Open with for video files", "Language", "Installation folder", "Existing default apps and personal language settings are kept. Administrator permission is required.", "Install", "Cancel", "Installing. Please wait.", "Installation completed.", "Installation completed. Restart Windows later.", "Installation failed. See the log below for details.", "Enter a valid full path to a local installation folder.", "Installation log", "Close", "Installation was cancelled." } },
            { "ja", new[] { "セットアップ", "言語とオプションを選び、インストールを押してください。", "デスクトップにショートカットを作成", "動画の「プログラムから開く」に登録", "言語", "インストール先", "既定のアプリと個人の言語設定は維持されます。管理者権限が必要です。", "インストール", "キャンセル", "インストール中です。お待ちください。", "インストールが完了しました。", "インストールが完了しました。後でWindowsを再起動してください。", "インストールに失敗しました。詳細は下のログを確認してください。", "有効なローカルフォルダーの絶対パスを入力してください。", "インストールログ", "閉じる", "インストールはキャンセルされました。" } },
            { "zh-Hans", new[] { "安装", "请选择语言和选项，然后点击安装。", "创建桌面快捷方式", "注册为视频文件的打开方式", "语言", "安装文件夹", "保留现有默认应用和个人语言设置。安装需要管理员权限。", "安装", "取消", "正在安装，请稍候。", "安装完成。", "安装完成。请稍后重新启动Windows。", "安装失败。请查看下方日志了解详情。", "请输入有效的本地安装文件夹完整路径。", "安装日志", "关闭", "安装已取消。" } },
            { "zh-Hant", new[] { "安裝", "請選擇語言與選項，然後按下安裝。", "建立桌面捷徑", "註冊為影片檔案的開啟程式", "語言", "安裝資料夾", "保留現有預設應用程式與個人語言設定。安裝需要系統管理員權限。", "安裝", "取消", "正在安裝，請稍候。", "安裝完成。", "安裝完成。請稍後重新啟動Windows。", "安裝失敗。請查看下方記錄了解詳情。", "請輸入有效的本機安裝資料夾完整路徑。", "安裝記錄", "關閉", "安裝已取消。" } },
            { "es", new[] { "Instalación", "Seleccione el idioma y las opciones y pulse Instalar.", "Crear un acceso directo en el escritorio", "Registrar en Abrir con para archivos de vídeo", "Idioma", "Carpeta de instalación", "Se conservan las aplicaciones predeterminadas y el idioma personal. Se requieren permisos de administrador.", "Instalar", "Cancelar", "Instalando. Espere, por favor.", "Instalación completada.", "Instalación completada. Reinicie Windows más tarde.", "La instalación ha fallado. Consulte el registro de abajo.", "Introduzca una ruta local completa y válida para la instalación.", "Registro de instalación", "Cerrar", "Se canceló la instalación." } },
            { "fr", new[] { "Installation", "Choisissez la langue et les options, puis cliquez sur Installer.", "Créer un raccourci sur le bureau", "Ajouter à Ouvrir avec pour les fichiers vidéo", "Langue", "Dossier d’installation", "Les applications par défaut et la langue personnelle sont conservées. Des droits d’administrateur sont nécessaires.", "Installer", "Annuler", "Installation en cours. Veuillez patienter.", "Installation terminée.", "Installation terminée. Redémarrez Windows ultérieurement.", "Échec de l’installation. Consultez le journal ci-dessous.", "Saisissez un chemin local complet et valide pour l’installation.", "Journal d’installation", "Fermer", "L’installation a été annulée." } },
            { "de", new[] { "Installation", "Sprache und Optionen auswählen, dann auf Installieren klicken.", "Desktopverknüpfung erstellen", "Für Videodateien unter Öffnen mit registrieren", "Sprache", "Installationsordner", "Standard-Apps und persönliche Spracheinstellungen bleiben erhalten. Administratorrechte sind erforderlich.", "Installieren", "Abbrechen", "Installation läuft. Bitte warten.", "Installation abgeschlossen.", "Installation abgeschlossen. Starten Sie Windows später neu.", "Installation fehlgeschlagen. Einzelheiten stehen im Protokoll unten.", "Geben Sie einen gültigen vollständigen lokalen Installationspfad ein.", "Installationsprotokoll", "Schließen", "Die Installation wurde abgebrochen." } },
            { "pt-BR", new[] { "Instalação", "Escolha o idioma e as opções e clique em Instalar.", "Criar atalho na área de trabalho", "Registrar em Abrir com para arquivos de vídeo", "Idioma", "Pasta de instalação", "Os aplicativos padrão e o idioma pessoal serão mantidos. É necessária permissão de administrador.", "Instalar", "Cancelar", "Instalando. Aguarde.", "Instalação concluída.", "Instalação concluída. Reinicie o Windows mais tarde.", "A instalação falhou. Consulte o registro abaixo.", "Digite um caminho local completo e válido para a instalação.", "Registro de instalação", "Fechar", "A instalação foi cancelada." } },
            { "ru", new[] { "Установка", "Выберите язык и параметры, затем нажмите «Установить».", "Создать ярлык на рабочем столе", "Добавить в «Открыть с помощью» для видеофайлов", "Язык", "Папка установки", "Приложения по умолчанию и личные настройки языка сохранятся. Нужны права администратора.", "Установить", "Отмена", "Идёт установка. Подождите.", "Установка завершена.", "Установка завершена. Перезапустите Windows позже.", "Ошибка установки. Подробности в журнале ниже.", "Введите полный допустимый путь к локальной папке установки.", "Журнал установки", "Закрыть", "Установка отменена." } },
            { "ar", new[] { "التثبيت", "اختر اللغة والخيارات ثم اضغط على تثبيت.", "إنشاء اختصار على سطح المكتب", "التسجيل ضمن فتح باستخدام لملفات الفيديو", "اللغة", "مجلد التثبيت", "سيتم الاحتفاظ بالتطبيقات الافتراضية وإعدادات اللغة الشخصية. يلزم إذن المسؤول.", "تثبيت", "إلغاء", "جارٍ التثبيت. يرجى الانتظار.", "اكتمل التثبيت.", "اكتمل التثبيت. أعد تشغيل Windows لاحقًا.", "فشل التثبيت. راجع السجل أدناه للتفاصيل.", "أدخل مسارًا محليًا كاملاً وصالحًا لمجلد التثبيت.", "سجل التثبيت", "إغلاق", "تم إلغاء التثبيت." } },
            { "hi", new[] { "स्थापना", "भाषा और विकल्प चुनें, फिर इंस्टॉल करें पर क्लिक करें।", "डेस्कटॉप शॉर्टकट बनाएँ", "वीडियो फ़ाइलों के लिए इसके साथ खोलें में जोड़ें", "भाषा", "स्थापना फ़ोल्डर", "मौजूदा डिफ़ॉल्ट ऐप और व्यक्तिगत भाषा सेटिंग बनी रहेंगी। व्यवस्थापक की अनुमति चाहिए।", "इंस्टॉल करें", "रद्द करें", "स्थापना जारी है। कृपया प्रतीक्षा करें।", "स्थापना पूरी हुई।", "स्थापना पूरी हुई। बाद में Windows फिर से शुरू करें।", "स्थापना विफल रही। विवरण के लिए नीचे लॉग देखें।", "स्थानीय स्थापना फ़ोल्डर का मान्य पूरा पथ दर्ज करें।", "स्थापना लॉग", "बंद करें", "स्थापना रद्द की गई।" } },
            { "it", new[] { "Installazione", "Scegli lingua e opzioni, poi premi Installa.", "Crea un collegamento sul desktop", "Registra in Apri con per i file video", "Lingua", "Cartella di installazione", "Le app predefinite e la lingua personale vengono mantenute. Sono necessari i permessi di amministratore.", "Installa", "Annulla", "Installazione in corso. Attendere.", "Installazione completata.", "Installazione completata. Riavvia Windows in seguito.", "Installazione non riuscita. Consulta il registro qui sotto.", "Inserisci un percorso locale completo e valido per l’installazione.", "Registro di installazione", "Chiudi", "Installazione annullata." } },
            { "id", new[] { "Instalasi", "Pilih bahasa dan opsi, lalu klik Instal.", "Buat pintasan desktop", "Daftarkan di Buka dengan untuk berkas video", "Bahasa", "Folder instalasi", "Aplikasi bawaan dan pengaturan bahasa pribadi tetap dipertahankan. Izin administrator diperlukan.", "Instal", "Batal", "Sedang menginstal. Harap tunggu.", "Instalasi selesai.", "Instalasi selesai. Mulai ulang Windows nanti.", "Instalasi gagal. Lihat log di bawah untuk detailnya.", "Masukkan jalur lokal lengkap yang valid untuk folder instalasi.", "Log instalasi", "Tutup", "Instalasi dibatalkan." } },
            { "vi", new[] { "Cài đặt", "Chọn ngôn ngữ và tùy chọn, rồi nhấn Cài đặt.", "Tạo lối tắt trên màn hình nền", "Đăng ký trong Mở bằng cho tệp video", "Ngôn ngữ", "Thư mục cài đặt", "Giữ nguyên ứng dụng mặc định và ngôn ngữ cá nhân. Cần quyền quản trị viên.", "Cài đặt", "Hủy", "Đang cài đặt. Vui lòng đợi.", "Đã cài đặt xong.", "Đã cài đặt xong. Hãy khởi động lại Windows sau.", "Cài đặt thất bại. Xem nhật ký bên dưới để biết chi tiết.", "Nhập đường dẫn đầy đủ hợp lệ đến thư mục cài đặt cục bộ.", "Nhật ký cài đặt", "Đóng", "Đã hủy cài đặt." } },
            { "th", new[] { "การติดตั้ง", "เลือกภาษาและตัวเลือก แล้วคลิกติดตั้ง", "สร้างทางลัดบนเดสก์ท็อป", "ลงทะเบียนในเปิดด้วยสำหรับไฟล์วิดีโอ", "ภาษา", "โฟลเดอร์ติดตั้ง", "คงแอปเริ่มต้นและการตั้งค่าภาษาส่วนตัวไว้ ต้องได้รับสิทธิ์ผู้ดูแลระบบ", "ติดตั้ง", "ยกเลิก", "กำลังติดตั้ง โปรดรอสักครู่", "ติดตั้งเสร็จแล้ว", "ติดตั้งเสร็จแล้ว โปรดเริ่ม Windows ใหม่ภายหลัง", "ติดตั้งไม่สำเร็จ ดูรายละเอียดในบันทึกด้านล่าง", "ป้อนพาธแบบเต็มที่ถูกต้องของโฟลเดอร์ติดตั้งในเครื่อง", "บันทึกการติดตั้ง", "ปิด", "ยกเลิกการติดตั้งแล้ว" } },
            { "tr", new[] { "Kurulum", "Dili ve seçenekleri seçip Yükle düğmesine tıklayın.", "Masaüstü kısayolu oluştur", "Video dosyaları için Birlikte aç listesine ekle", "Dil", "Kurulum klasörü", "Varsayılan uygulamalar ve kişisel dil ayarları korunur. Yönetici izni gerekir.", "Yükle", "İptal", "Yükleniyor. Lütfen bekleyin.", "Kurulum tamamlandı.", "Kurulum tamamlandı. Windows’u daha sonra yeniden başlatın.", "Kurulum başarısız. Ayrıntılar için aşağıdaki günlüğe bakın.", "Geçerli bir yerel kurulum klasörünün tam yolunu girin.", "Kurulum günlüğü", "Kapat", "Kurulum iptal edildi." } },
            { "pl", new[] { "Instalacja", "Wybierz język i opcje, a następnie kliknij Zainstaluj.", "Utwórz skrót na pulpicie", "Dodaj do Otwórz za pomocą dla plików wideo", "Język", "Folder instalacji", "Domyślne aplikacje i osobiste ustawienia języka zostaną zachowane. Wymagane są uprawnienia administratora.", "Zainstaluj", "Anuluj", "Trwa instalacja. Proszę czekać.", "Instalacja zakończona.", "Instalacja zakończona. Uruchom ponownie Windows później.", "Instalacja nie powiodła się. Szczegóły w dzienniku poniżej.", "Wprowadź prawidłową pełną ścieżkę do lokalnego folderu instalacji.", "Dziennik instalacji", "Zamknij", "Instalacja została anulowana." } },
        };
        public static string Get(string language, string key)
        {
            int index = Array.IndexOf(Keys, key);
            if (index < 0) throw new ArgumentException("Unknown installer text: " + key);
            return Texts[CodeMonkeyPlayer.UiText.Normalize(language)][index];
        }
    }
}
